### ISSUE TITLE
ImportError: cannot import name 'read_calib_file'

### ISSUE THREAD

**Issue by HXB-1997** [IIPCVLAB/LCCNet#27]
(lccnet0127) x12spa@x12spa-Super-Server:~/Desktop/HXB/LCCNet0127/LCCNet$ python3 evaluate_calib.py 
Traceback (most recent call last):
  File "evaluate_calib.py", line 34, in <module>
    from DatasetLidarCamera import DatasetLidarCameraKittiOdometry
  File "/home/x12spa/Desktop/HXB/LCCNet0127/LCCNet/DatasetLidarCamera.py", line 27, in <module>
    from utils import invert_pose, rotate_forward, quaternion_from_matrix, read_calib_file
ImportError: cannot import name 'read_calib_file'

**Comment by XWGuo99** [comment]
Same problem here.
'read_calib_file' is mentioned in 'DatasetLidarCamera.py'
` from utils import invert_pose, rotate_forward, quaternion_from_matrix, read_calib_file
`
However 'read_calib_file' is not found in 'utils.py'
